# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRepository: 'mabahloul/dockerhubdemo'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
      demands:
        - agent.os -equals Linux
    steps:
    - task: Docker@2
      displayName: Build and push an image to Docker Hub
      inputs:
        command: buildAndPush
        repository: '$(dockerRepository)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
        containerRegistry: 'dockerconnection'
